application: nss-app
version: 2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: off
- remote_api: off
- deferred: on

libraries:
- name: jinja2
  version: "latest"
- name: lxml
  version: "2.3"   # or "latest"

#~ inbound_services:
#~ - mail

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*

- url: /static
  static_dir: static
- url: /assets
  static_dir: templates_assets

#- url: /-/api.*
# script: services.application

- url: /(cron|task)/.*
  login: admin
  script: main.application

- url: /.*
  script: main.application
  #~ http_headers:
    #~ X-Foo-Header: foo
    #~ X-Bar-Header: bar value
#~ 
#~ - url: /_ah/mail/.+
  #~ script: handle_incoming_email.app
  #~ login: admin
